### PR TITLE
Upgrade faker from 0.16.0 to 0.17.0

### PR DESCRIPTION
**Pull request by niels**
For Elixir 1.13 compatibility.

With v0.16.0, the project fails to compile on Elixir 1.13.0:

```elixir
❯ mix deps.compile
==> faker
Compiling 102 files (.ex)

== Compilation error in file lib/faker/string.ex ==
** (SyntaxError) lib/faker/string.ex:144:15: invalid bidirectional formatting character in string: \u202A. If you want to use such character, use it in its escaped \u202A form instead
    (elixir 1.13.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :faker, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile faker", update it with "mix deps.update faker" or clean it with "mix deps.clean faker"
```

See https://github.com/elixirs/faker/pull/434.

### CODE REVIEW

**Comment by vheathen** [comment]
@niels Thanks a lot!
